sudo: required

services:
    - docker

before_install:
    - docker build -t maedoc/test-docker .

script:
    - ls

after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push maedoc/test-docker
